backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Блог"
    label_singular: "Пост"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} — {{date}}"
    fields:
      - label: "Шаблон"
        name: "layout"
        widget: "hidden"
        default: "detail_blog"
      - label: "Заголовок"
        name: "title"
        widget: "string"
      - label: "Автор"
        name: "author"
        widget: "relation"
        collection: "team"
        search_fields: ["name", "position"]
        value_field: "{{slug}}"
        display_fields: ["name", "position"]
      - label: "Дата"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: false
        format: "YYYY-MM-DD"
      - label: "Обложка"
        name: "cover"
        widget: "image"
      - label: "Краткое описание"
        name: "summary"
        widget: "text"
        required: false
      - label: "Written by"
        name: "written_by"
        widget: "string"
        required: false
      - label: "Текст статьи"
        name: "body"
        widget: "markdown"

  - name: "team"
    label: "Сотрудники"
    label_singular: "Сотрудник"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    summary: "{{name}} — {{position}}"
    fields:
      - label: "Шаблон"
        name: "layout"
        widget: "hidden"
        default: "detail_team"

      - label: "Имя"
        name: "name"
        widget: "string"

      - label: "Должность"
        name: "position"
        widget: "string"

      - label: "Фото"
        name: "photo"
        widget: "image"